import hmac
import os

SERVICE_TOKEN_HEADER = "X-LabsConnect-Service-Token"


class ServiceTokenError(Exception):
    """Raised when a service-to-service call is not authorised."""

    def __init__(self, status_code: int, detail: str) -> None:
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


def check_service_token(*, configured: str, presented: str | None) -> None:
    """Fail closed. An unset token refuses every caller rather than admitting all.

    A whitespace-only configured value is treated as unset, not as a real
    secret to compare against. The presented value is never stripped.

    The comparison is done on bytes, not str, because hmac.compare_digest
    refuses non-ASCII str operands and raises TypeError rather than
    returning False. A header value can carry any byte 0x00-0xFF; ASGI
    servers (Starlette included) decode raw header bytes as latin-1, which
    never raises, so a non-ASCII presented value reaches this function as a
    normal Python str and must be refused, not allowed to crash the route.
    Encoding both sides with latin-1 (rather than utf-8) exactly reverses
    that decode: it reproduces the literal bytes that arrived on the wire
    for presented, instead of silently re-expanding any non-ASCII character
    into a different, longer UTF-8 byte sequence. The configured secret is
    documented as generated by `openssl rand -hex 32`, i.e. plain ASCII hex,
    so latin-1 and utf-8 encode it identically; the choice only changes
    behavior for a malformed presented value, where latin-1 stays faithful
    to what was actually sent.
    """
    configured = configured.strip()
    if not configured:
        raise ServiceTokenError(503, "service token is not configured")
    if not presented:
        raise ServiceTokenError(403, "service token required")
    try:
        matches = hmac.compare_digest(
            presented.encode("latin-1"), configured.encode("latin-1")
        )
    except UnicodeEncodeError:
        # Cannot originate from a real HTTP header (latin-1 decode always
        # round-trips), but a direct caller could pass a str outside the
        # latin-1 range. Treat it the same as any other non-matching token.
        matches = False
    if not matches:
        raise ServiceTokenError(403, "service token required")


def service_token() -> str:
    return os.getenv("LAB_API_SERVICE_TOKEN", "")


def service_headers() -> dict[str, str]:
    token = service_token()
    return {SERVICE_TOKEN_HEADER: token} if token else {}
